import type { Metadata } from "next";
import {JetBrains_Mono} from "next/font/google";
import "./globals.css";
import Header from '@/app/Components/Header'
import PageTransition from "./ui/PageTransition";
import StairsTransition from "./ui/StairsTransition";


const jetbrainsMono =  JetBrains_Mono({
  subsets: ["latin"],
  weight:["100","200","300","400","500","600","700","800"],
  variable: '--font-jetbrainsMono',
  display: "swap",
});

export const metadata: Metadata = {
  title: "Brian Muchira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
      <Header />
      <StairsTransition/>
      <PageTransition>
         {children}
      </PageTransition>
      </body>
    </html>
  );
}
